server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: service-neo4j
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.neo4j.jdbc.bolt.BoltDriver
    url: jdbc:neo4j:bolt://172.16.4.82:7687
    username: neo4j
    password: smcaiot
    #   \u6570\u636E\u6E90\u5176\u4ED6\u914D\u7F6E
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #    validation-query: match (n) return id(n) limit 2
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
