spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.18.103.170:1521:orclcdr
      username: sinosoft_empi_standard_server
      password: sinosoft
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,logback,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT * from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 10.18.103.11
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    maxActive: 200
    maxWait: 3000
    maxIdle: 8
    minIdle: 0
    testOnBorrow: true
    clientName: root
    timeout: 3000

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file: D:\logs\${server.servlet.context-path}\catalina.log

zookeeper:
  address: 127.0.0.1:2181

dubbo:
#  scan:
#    base-packages: com.sinosoft.elasticjob.boot.service
  application:
    name: elasticjob-produce
  protocol:
    name: dubbo
#    port: ${dubbo_port:20884}
    port: 20883
  registry:
#    address: nacos://10.18.103.242:8848
    protocol: zookeeper
    address: ${zookeeper.address}
#  application:
#    qos-enable: false
  consumer:
    check: false

elasticjob:
  serverList: ${zookeeper.address}
  namespace: elastic-job-lite-springboot
  shardingTotalCount: 4
  shardingItemParameters: 0=0,1=1,2=0,3=1
  simpleJobCron: 0 0/30 1 * * ?
  empiMiddleJobCron: 0 0 2 * * ?

